name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the Angular app
        run: ng build --configuration production --base-href "https://divyaprakashmj20.github.io/scale-tech-no-standalone/"

      - name: Deploy to GitHub Pages
        run: npx angular-cli-ghpages --dir=dist/scale-tech-no-standalone 
